import type { ISODateTimeString } from "../utils/Timestamp.js";
import type { User } from "./User.js";
import type { Role } from "../Role/index.js";
import type { Org, OrgID } from "../Org/index.js";

/**
 * Type of a TeamInvitation object.
 */
export interface TeamInvitation {
  /**
   * Unique invitation ID.
   */
  id: number;

  /**
   * Created at datetime in ISO string format, generated by DB on insert.
   */
  createdAt: ISODateTimeString;

  /**
   * Invitee's email address.
   */
  inviteeEmail: User["email"];

  /**
   * Details of inviter that invited the user to join the team.
   */
  inviter: {
    name: User["name"];

    /**
     * Inviter has a role because they must be part of a team before they can
     * invite someone else to join, which means they must have a role.
     */
    role: Role;
  };

  /**
   * Details of the team that sent the invitation.
   */
  team: {
    /**
     * ID of the team the user is invited to join.
     */
    id: OrgID;

    /**
     * Name of the team the user is invited to join.
     */
    name: Org["name"];
  };
}
