# Reference: https://www.prisma.io/docs/guides/deployment/deploy-database-changes-with-prisma-migrate

name: Run Prisma migrations
run-name: ${{ github.actor }} is running DB migrations 🚀

on:
  workflow_call:
    secrets:
      DATABASE_URL:
        description: Database URL for Prisma to run migrations on. Must be a Direct URL.
        required: true

jobs:
  migrate-db:
    runs-on: ubuntu-latest

    # Use /server of the monorepo
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: "Running migrations using '${{ github.ref }}' branch"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          # Using node 18 to match engine version specified in /server/package.json
          node-version: "18"

      # Only install dependencies needed to run prisma migrations.
      - name: Install prisma dependencies
        # Install the major version's latest minor version to match version
        # specified in /server/package.json and to avoid breaking changes.
        run: npm install prisma@^5.x.x

      - name: Apply all pending migrations to the database
        run: npx prisma migrate deploy
        env:
          # Since not using Prisma's data proxy, the DATABASE_URL is a
          # DIRECT_URL, therefore they use the same secret here.
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DATABASE_URL }}
