name: Run Prisma migrations on PRODUCTION DB
run-name: ${{ github.actor }} is running prisma migrations on PRODUCTION DB 🚀

on:
  push:
    branches:
      - prod

jobs:
  migrate-db:
    uses: ./.github/workflows/prisma-migrate-db.yml
    secrets:
      DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
