name: PRODUCTION DB Prisma migrations
run-name: ${{ github.actor }} is running prisma migrations on PRODUCTION DB 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - prod
    paths:
      - "server/prisma/**"

jobs:
  migrate:
    uses: ./.github/workflows/prisma-migrate-db.yml
    secrets:
      DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
