name: STAGING DB Prisma migrations
run-name: ${{ github.actor }} is running prisma migrations on STAGING DB 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  migrate:
    uses: ./.github/workflows/prisma-migrate-db.yml
    secrets:
      DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
